# Label PRs based on changed file paths

documentation:
  - '**/*.md'
  - 'docs/**/*'

configuration:
  - '*.yml'
  - '*.yaml'
  - '.github/**/*'

scripts:
  - '**/*.sh'
  - '**/*.bash'

python:
  - '**/*.py'
  - 'pyproject.toml'
  - 'uv.lock'
