name: Sync

on:
  schedule:
    # Daily at 02:00 UTC
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run sync script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          PROFILE: ${{ secrets.PROFILE }}
        run: uv run python main.py
